import { Grant, Proposal, Milestone } from './types';

export const mockGrants: Grant[] = [
  {
    id: 'grant-1',
    title: 'STEM Education for Underserved Communities',
    description: 'Supporting innovative STEM education programs that reach underserved communities and promote diversity in tech.',
    amount: 25000,
    category: 'Education',
    deadline: '2025-12-31',
    status: 'open',
    donorId: 'donor-1',
    donorName: 'Tech for Good Foundation',
    eligibility: ['Non-profit organizations', 'Educational institutions', 'Community leaders'],
    requirements: ['Detailed project plan', 'Budget breakdown', 'Community impact assessment'],
    milestones: 3,
    applicantsCount: 12,
    fundsDistributed: 0,
    createdAt: '2025-09-15',
  },
  {
    id: 'grant-2',
    title: 'Clean Water Access Initiative',
    description: 'Funding projects that provide sustainable clean water solutions to rural communities.',
    amount: 50000,
    category: 'Environment',
    deadline: '2025-11-30',
    status: 'open',
    donorId: 'donor-2',
    donorName: 'Global Health Alliance',
    eligibility: ['NGOs', 'Community organizations', 'Social enterprises'],
    requirements: ['Technical feasibility study', 'Community engagement plan', 'Sustainability strategy'],
    milestones: 4,
    applicantsCount: 8,
    fundsDistributed: 0,
    createdAt: '2025-08-20',
  },
  {
    id: 'grant-3',
    title: 'Women Entrepreneurs Accelerator',
    description: 'Micro-grants for women-led startups in emerging markets to scale their businesses.',
    amount: 10000,
    category: 'Entrepreneurship',
    deadline: '2025-10-31',
    status: 'open',
    donorId: 'donor-1',
    donorName: 'Tech for Good Foundation',
    eligibility: ['Women entrepreneurs', 'Early-stage startups', 'Emerging market businesses'],
    requirements: ['Business plan', 'Financial projections', 'Impact metrics'],
    milestones: 2,
    applicantsCount: 25,
    fundsDistributed: 0,
    createdAt: '2025-09-01',
  },
  {
    id: 'grant-4',
    title: 'Youth Mental Health Support Programs',
    description: 'Supporting innovative mental health programs for young people aged 13-25.',
    amount: 15000,
    category: 'Healthcare',
    deadline: '2026-01-31',
    status: 'in_progress',
    donorId: 'donor-3',
    donorName: 'Wellness Foundation',
    eligibility: ['Healthcare providers', 'Youth organizations', 'Mental health professionals'],
    requirements: ['Program description', 'Qualification evidence', 'Impact measurement plan'],
    milestones: 3,
    applicantsCount: 15,
    fundsDistributed: 5000,
    createdAt: '2025-07-10',
  },
  {
    id: 'grant-5',
    title: 'Blockchain Education & Adoption',
    description: 'Educational programs to increase blockchain literacy and adoption in developing regions.',
    amount: 20000,
    category: 'Technology',
    deadline: '2025-12-15',
    status: 'open',
    donorId: 'donor-4',
    donorName: 'Decentralized Future DAO',
    eligibility: ['Tech educators', 'Community organizations', 'Educational startups'],
    requirements: ['Curriculum outline', 'Target audience analysis', 'Success metrics'],
    milestones: 3,
    applicantsCount: 18,
    fundsDistributed: 0,
    createdAt: '2025-08-05',
  },
];

export const mockProposals: Proposal[] = [
  {
    id: 'proposal-1',
    grantId: 'grant-1',
    grantTitle: 'STEM Education for Underserved Communities',
    applicantId: 'applicant-1',
    applicantName: 'Maria Rodriguez',
    title: 'Mobile STEM Labs for Rural Schools',
    description: 'Creating mobile STEM laboratories that travel to rural schools, bringing hands-on science education to 500+ students.',
    requestedAmount: 25000,
    status: 'approved',
    milestones: [
      {
        id: 'milestone-1',
        proposalId: 'proposal-1',
        title: 'Equipment Procurement & Lab Setup',
        description: 'Purchase equipment and convert vehicle into mobile lab',
        amount: 10000,
        status: 'verified',
        dueDate: '2025-11-15',
        submittedAt: '2025-11-10',
        verifiedAt: '2025-11-12',
        verifierNotes: 'All equipment verified. Lab setup meets requirements.',
        evidence: 'Equipment receipts and photos submitted',
      },
      {
        id: 'milestone-2',
        proposalId: 'proposal-1',
        title: 'Pilot Program - 5 Schools',
        description: 'Launch pilot program in 5 schools, gather feedback',
        amount: 8000,
        status: 'submitted',
        dueDate: '2025-12-20',
        submittedAt: '2025-12-18',
        evidence: 'Photos, attendance records, and student feedback forms',
      },
      {
        id: 'milestone-3',
        proposalId: 'proposal-1',
        title: 'Full Program Rollout',
        description: 'Expand to 15 schools, complete curriculum',
        amount: 7000,
        status: 'pending',
        dueDate: '2026-01-30',
      },
    ],
    submittedAt: '2025-09-20',
    verifierId: 'verifier-1',
  },
  {
    id: 'proposal-2',
    grantId: 'grant-2',
    grantTitle: 'Clean Water Access Initiative',
    applicantId: 'applicant-2',
    applicantName: 'John Kimani',
    title: 'Solar-Powered Water Purification System',
    description: 'Installing solar-powered water purification systems in 3 villages, providing clean water to 2,000+ residents.',
    requestedAmount: 45000,
    status: 'in_progress',
    milestones: [
      {
        id: 'milestone-4',
        proposalId: 'proposal-2',
        title: 'Site Assessment & Design',
        description: 'Complete site surveys and system design',
        amount: 8000,
        status: 'verified',
        dueDate: '2025-10-30',
        submittedAt: '2025-10-25',
        verifiedAt: '2025-10-28',
        verifierNotes: 'Comprehensive site assessment completed',
      },
      {
        id: 'milestone-5',
        proposalId: 'proposal-2',
        title: 'Installation - Village 1',
        description: 'Install first purification system',
        amount: 15000,
        status: 'submitted',
        dueDate: '2025-11-30',
        submittedAt: '2025-11-28',
        evidence: 'Installation photos and water quality test results',
      },
      {
        id: 'milestone-6',
        proposalId: 'proposal-2',
        title: 'Installation - Villages 2 & 3',
        description: 'Complete remaining installations',
        amount: 22000,
        status: 'pending',
        dueDate: '2026-01-15',
      },
    ],
    submittedAt: '2025-09-10',
    verifierId: 'verifier-2',
  },
  {
    id: 'proposal-3',
    grantId: 'grant-3',
    grantTitle: 'Women Entrepreneurs Accelerator',
    applicantId: 'applicant-3',
    applicantName: 'Aisha Patel',
    title: 'Sustainable Fashion Platform',
    description: 'Building an online marketplace connecting rural women artisans with global customers.',
    requestedAmount: 10000,
    status: 'pending',
    milestones: [
      {
        id: 'milestone-7',
        proposalId: 'proposal-3',
        title: 'Platform Development',
        description: 'Develop MVP platform and onboard first artisans',
        amount: 5000,
        status: 'pending',
        dueDate: '2025-11-30',
      },
      {
        id: 'milestone-8',
        proposalId: 'proposal-3',
        title: 'Marketing & Growth',
        description: 'Launch marketing campaign and scale to 50 artisans',
        amount: 5000,
        status: 'pending',
        dueDate: '2025-12-31',
      },
    ],
    submittedAt: '2025-10-05',
  },
];
